# Generated by Django 5.2.6 on 2025-09-25 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_author_alter_uupload_image_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pic',
        ),
    ]
